test-dotnet-app-mvc/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using test_dotnet_app_mvc.Controllers.Service;
using test_dotnet_app_mvc.Models;

namespace test_dotnet_app_mvc.Controllers
{
    public class HotelController : Controller
    {
        private readonly MyDbContext _context;

        public HotelController(MyDbContext context)
        {
            _context = context;


        }
        public IActionResult Index()
        {
            HotelService cs = new HotelService(_context);
            var result = cs.GetHotels();

            var hotels = new List<Hotel>();
            foreach (var p in result.Result.Value)
            {
                Hotel hotel = new Hotel();
                hotel.ID = p.ID;
                hotel.NAME = p.NAME;
                hotel.DESCRIPTION = p.DESCRIPTION;
                hotel.IMAGEURL = p.IMAGEURL;
                //hotel.PRICE = p.PRICE;
                hotels.Add(hotel);
            }

            return View(hotels);
        }


        public IActionResult Edit(int id)
        {
            var hotel = _context.Hotel.Find(id);
            return View(hotel);
        }

        [HttpPost]
        public IActionResult Edit(Hotel hotel)
        {
            _context.Hotel.Update(hotel);
            _context.SaveChanges();
            return RedirectToAction("Manage", "Admin");
        }

        // GET: Hotel/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        // POST: Hotel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hotel = await _context.Hotel.FindAsync(id);
            _context.Hotel.Remove(hotel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Detail(int id)
        {
            var hotel = _context.Hotel.ToList().Where(x => x.ID == id).FirstOrDefault();
            return View(hotel);
        }


    }
}

test-dotnet-app-mvc/Views/Admin/CreateCruise.cshtml
@model test_dotnet_app_mvc.Models.Cruise

@{
    ViewBag.Title = "Add New Cruise";
}

@*<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>*@

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NAME)
        @Html.TextBoxFor(model => model.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.NAME)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DESCRIPTION)
        @Html.TextBoxFor(model => model.DESCRIPTION, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DESCRIPTION)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IMAGEURL)
        @Html.TextBoxFor(model => model.IMAGEURL, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IMAGEURL)
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.State)
        @Html.TextBoxFor(model => model.State, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.State)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country)
        @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Country)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber)
        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>*@

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add Cruise</button>
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-link" })
    </div>
}


<script>
    $(document).ready(function () {

        updateActiveNavToAdmin();

    });
</script>

test-dotnet-app-mvc/Views/Admin/CreateFlight.cshtml
@model test_dotnet_app_mvc.Models.Flight

@{
    ViewBag.Title = "Add New Flight";
}

@*<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>*@

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NAME)
        @Html.TextBoxFor(model => model.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.NAME)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DESCRIPTION)
        @Html.TextBoxFor(model => model.DESCRIPTION, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DESCRIPTION)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IMAGEURL)
        @Html.TextBoxFor(model => model.IMAGEURL, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IMAGEURL)
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.State)
        @Html.TextBoxFor(model => model.State, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.State)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country)
        @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Country)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber)
        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>*@

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add Flight</button>
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-link" })
    </div>
}


<script>
    $(document).ready(function () {

        updateActiveNavToAdmin();

    });
</script>

test-dotnet-app-mvc/Views/Admin/CreateHotel.cshtml
@model test_dotnet_app_mvc.Models.Hotel

@{
    ViewBag.Title = "Add New Hotel";
}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NAME)
        @Html.TextBoxFor(model => model.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.NAME)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DESCRIPTION)
        @Html.TextBoxFor(model => model.DESCRIPTION, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DESCRIPTION)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IMAGEURL)
        @Html.TextBoxFor(model => model.IMAGEURL, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IMAGEURL)
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.State)
        @Html.TextBoxFor(model => model.State, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.State)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country)
        @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Country)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber)
        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>*@

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add Hotel</button>
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-link" })
    </div>
}


<script>
    $(document).ready(function () {

        updateActiveNavToAdmin();

    });
</script>

test-dotnet-app-mvc/Views/Admin/CreatePlace.cshtml
@model test_dotnet_app_mvc.Models.Place

@{
    ViewBag.Title = "添加新目的地";
}

@*<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>*@

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NAME)
        @Html.TextBoxFor(model => model.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.NAME)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DESCRIPTION)
        @Html.TextBoxFor(model => model.DESCRIPTION, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DESCRIPTION)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IMAGEURL)
        @Html.TextBoxFor(model => model.IMAGEURL, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IMAGEURL)
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.State)
        @Html.TextBoxFor(model => model.State, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.State)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country)
        @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Country)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber)
        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>*@

    <div class="form-group">
        <button type="submit" class="btn btn-primary">添加目的地</button>
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-link" })
    </div>
}


<script>
    $(document).ready(function () {

        updateActiveNavToAdmin();

    });
</script>

test-dotnet-app-mvc/Views/Admin/CreateUser.cshtml
@model test_dotnet_app_mvc.Models.User

@{
    ViewBag.Title = "Add New User";
}

@*<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>*@

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.DESCRIPTION)
        @Html.TextBoxFor(model => model.DESCRIPTION, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DESCRIPTION)
    </div>

   
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add User</button>
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-link" })
    </div>
}


<script>
    $(document).ready(function () {

        updateActiveNavToAdmin();

    });
</script>

test-dotnet-app-mvc/Views/Admin/Manage.cshtml
@model AllInfo
@{
    ViewBag.Title = "Manage";
    Layout = "_Layout";

}

@*<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>*@

<div class="container">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" id="hotels-tab" data-toggle="tab" href="#hotels" role="tab" aria-controls="hotels" aria-selected="true">Hotels</a>
        </li>
        <li class="nav-item" id="Tab2">
            <a class="nav-link" id="places-tab" data-toggle="tab" href="#places" role="tab" aria-controls="places" aria-selected="false">Destinations</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cruises-tab" data-toggle="tab" href="#cruises" role="tab" aria-controls="cruises" aria-selected="false">Cruises</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="users-tab" data-toggle="tab" href="#users" role="tab" aria-controls="users" aria-selected="false">Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="products-tab" data-toggle="tab" href="#products" role="tab" aria-controls="products" aria-selected="false">产品管理</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="hotels" role="tabpanel" aria-labelledby="hotels-tab">
            <!-- content for hotels tab goes here -->
            <div class="container">
                <p>
                    <a asp-action="CreateHotel">Add Hotel</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Hotel Name</th>
                            <th>Description</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var hotel in Model.Hotels)
                        {
                            <tr>
                                <td>@hotel.ID</td>
                                <td>@hotel.NAME</td>
                                <td>@hotel.DESCRIPTION</td>
                                <td>
                                    <a asp-controller="Hotel" asp-action="Detail" asp-route-id="@hotel.ID">Detail</a>
                                </td>
                                <td>
                                    <a asp-controller="Hotel" asp-action="Edit" asp-route-id="@hotel.ID">Edit</a>
                                </td>
                                <td>
                                    <form asp-controller="Hotel" asp-action="Delete" asp-route-id="@hotel.ID" method="get">
                                        <button type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="places" role="tabpanel" aria-labelledby="places-tab">
            <!-- content for flights tab goes here -->
            <div class="container">
                <p>
                    <a asp-action="CreatePlace">Add Place</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var place in Model.Places)
                        {
                            <tr>
                                <td>@place.ID</td>
                                <td>@place.NAME</td>
                                <td>@place.DESCRIPTION</td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@place.ID">Edit</a>
                                </td>
                                <td>
                                    <form asp-action="Delete" asp-route-id="@place.ID" method="post">
                                        <button type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="cruises" role="tabpanel" aria-labelledby="cruises-tab">
            <!-- content for cruises tab goes here -->
            <div class="container">
                <p>
                    <a asp-action="CreateCruise">Add Cruise</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Cruise Name</th>
                            <th>Description</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var cruise in Model.Cruises)
                        {
                            <tr>
                                <td>@cruise.ID</td>
                                <td>@cruise.NAME</td>
                                <td>@cruise.DESCRIPTION</td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@cruise.ID">Edit</a>
                                </td>
                                <td>
                                    <form asp-action="Delete" asp-route-id="@cruise.ID" method="post">
                                        <button type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div class="tab-pane fade" id="users" role="tabpanel" aria-labelledby="users-tab">
            <!-- content for cruises tab goes here -->
            <div class="container">
                <p>
                    <a asp-action="CreateUser">Add User</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Description</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model.Users)
                        {
                            <tr>
                                <td>@user.ID</td>

                                <td>@user.DESCRIPTION</td>
                                <td>
                                    <a asp-controller="User" asp-action="Edit" asp-route-id="@user.ID">Edit</a>
                                </td>
                                <td>
                                    <form asp-controller="User" asp-action="Delete" asp-route-id="@user.ID" method="post">
                                        <button type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div class="tab-pane fade" id="products" role="tabpanel" aria-labelledby="products-tab">
            <!-- content for cruises tab goes here -->
            <div class="container">
                <p>
                    <a asp-action="CreateProduct">添加新产品</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>编号</th>
                            <th>名称</th>
                            <th>类型</th>
                            <th>排序</th>
                            <th>編輯</th>
                            <th>刪除</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.Products)
                        {
                            <tr>
                                <td>@product.ID</td>
                                <td>@product.NAME</td>
                                <td>@product.TYPE</td>
                                <td>@product.ORDER</td>
                                <td>
                                    <a asp-controller="Product" asp-action="Edit" asp-route-id="@product.ID">編輯</a>
                                </td>
                                <td>
                                    <form asp-controller="Product" asp-action="Delete" asp-route-id="@product.ID" method="post">
                                        <button type="submit">刪除</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>